name: Update APOD

on:
  schedule:
    - cron: '0 8 * * *'  # Run every day at 8 AM UTC
    
permissions:
  contents: write  # Allow push permissions to the repository


jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests
          pip install python-dotenv  # Install python-dotenv

      - name: Run script
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }} 
        run: python update_apod.py
